### ISSUE TITLE
Created New Keyboard

### ISSUE THREAD

**Issue by serjooo** [kostub/MathEditor#4]
Hello,

I created a new keyboard the same way you have made the keyboard. However, the keyboard I created has integrals, ointegrals, summations, limits, and many other special characters which are included in Latex. However, the MTEditableMathLabel is not drawing these special characters. I noticed since you have technically mapped in the code how each fractions, superscripts, subscripts it will draw them correctly accordingly given the cases, doing it this way will not be maintainable in the long run. Is there a way we can pass any latex and have it drawn and made editable correctly without having to go through the hassle of writing code for each new button or functionality added? I am trying to achieve a keyboard similar to PhotoMath with more functionalities and keys.

(Also I admit I might be wrong in the way I have analyzed your code, maybe I did something wrong)

**Comment by kostub** [comment]
Most of the mapping of fractions, super/subscripts etc. is for editing and modifying the underlying LaTeX and for positioning and figuring out where the cursor is. Is there a better way to do that? To just render the latex directly you can use `iosMath`.

**Comment by serjooo** [comment]
I closed this issue because I noticed I'm an idiot for asking that question. As I went deeper in the code realized it was being the right way. Anyways I removed integrals and all the extra functionalities from the keyboard since turns out we no longer need it in our app. However, once I'm free I'll be happy to help make a new keyboard with all those added functionalities. We would need to do the same I you have done with all the other types. 

For integral for example, it has a subscript, superscript and it has its own body which can contain anything, and so on. An empty square would be placed for each as placeholders and make those parts editable. 

We can also later add the functionality of navigating through editable parts of the equation using arrows looking for the empty square unicode in the whole tree.

**Comment by pratikgajbhiye222** [comment]
> I closed this issue because I noticed I'm an idiot for asking that question. As I went deeper in the code realized it was being the right way. Anyways I removed integrals and all the extra functionalities from the keyboard since turns out we no longer need it in our app. However, once I'm free I'll be happy to help make a new keyboard with all those added functionalities. We would need to do the same I you have done with all the other types.
> 
> For integral for example, it has a subscript, superscript and it has its own body which can contain anything, and so on. An empty square would be placed for each as placeholders and make those parts editable.
> 
> We can also later add the functionality of navigating through editable parts of the equation using arrows looking for the empty square unicode in the whole tree.

Can you please tell me how add integration sign in keyboard of MathEditor ? and how can we add custom sign in keyboard?

**Comment by trung10101995** [comment]
@serjooo
"We can also later add the functionality of navigating through editable parts of the equation using arrows looking for the empty square unicode in the whole tree."

Please explain this in more detail.
