### ISSUE TITLE
Matrices, Custom keyboards and horizontal Scrolling

### ISSUE THREAD

**Issue by MFJones21** [kostub/MathEditor#7]
So first of, thank you so much for developing such an awesome Pod. It really solved a lot of my problems but I have a few things to still take care of and this seemed like the right place to ask.

Is it possible, and if yes how, to enter and edit matrices ?

How do I implement a custom keyboard in Swift ? I am writing my App in swift and I would like to make a custom keyboard. So I implemented the MTMathKeybard protocol but I can’t get info about what methods to implement.

When the Input gets wider then the width of the label theres currently (to my knowledge) to way to get back and forth. How would you go about this ?

I also have a little Question about your uneditable label but it is in the Issues threat of the Repository. But again, thank you so much for sharing this awesome work. I really am amazed by your work. 

All my best,
Jony

**Comment by kostub** [comment]
Sorry for the late response:

Editing matrices is not implemented. You will have to implement a custom keyboard to do that.

To implement a custom keyboard just implement the two methods on `MTMathKeyboard`. Look at `MTMathKeyboardRootView` code to see how those could implemented. Essentially they take an `UIKeyInput` as a parameter. Whenever your keyboard needs to update the label, it can call the `UIKeyInput` methods: `insertText` or `deleteBackwards`. Then set the `keyboard` property on the label with your custom keyboard.

To adjust the label when it gets too big look at `MTMathEditorExample`, that has code to adjust the size of the text.

Hope this helps.

**Comment by MFJones21** [comment]
Absolutely no problem =)
Thanks a lot for your answer. So I will play around with the custom keyboard and the example. But is there a way to change the textcolor of the editable label ? The tintColor doesn't seem to do the job.

And again. Thanks a lot for contributing to this awesome project.

**Comment by kostub** [comment]
To change the color of the text, set the `color` field on the `MathUILabel`. If you want to change the color of just part of text there is the `\textcolor` command you can use.
